# Use official OpenJDK image as base
FROM openjdk:17-jdk-slim

# Create app directory
WORKDIR /app

# Copy the jar file
COPY target/*.jar WeWill-1.0-SNAPSHOT.jar

# Run the jar
ENTRYPOINT ["java", "-jar", "WeWill-1.0-SNAPSHOT.jar"]
